import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import ActivePageContext from "@/context/activePageContext";
import { store } from "../store";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#EFF6FC]`}>
        <div className="flex w-full h-[100vh] justify-between items-center gap-6 p-6">
          <ActivePageContext>
            <Provider store={store}>
              {/* <NavBar /> */}
              {children}
            </Provider>
          </ActivePageContext>
        </div>
      </body>
    </html>
  );
}
